### ISSUE TITLE
バトランレビュー

### ISSUE THREAD

**Issue by hisaju** [tomomih217/dacode#5]
遅くなってしまい申し訳ございません。
※ 確認後closeしてください

## サービスレビュー

* 脱出ゲームみたいで面白かったです！（最後解けなかったですｗ）
* もうちょっと難易度下げてもらえると（解説増やしてもらえると）嬉しいですね。
* この方向感すごく引きがあって、採用担当者もハマりそうな気はするので、UI/UXをもう少し工夫して自然に回答出来たり、最初の問題だけチュートリアル的にクリアしやすくするともっとハマるんじゃないかなと思います。追加の問題も楽しみです！

## コードレビュー

https://github.com/tomomih217/dacode/blob/378e1a02836db9dcf5bac2359052de59348532fc/app/controllers/records_controller.rb#L16

こういったpathの書き方をされていましたが、ルーティング設定でasの設定をすると◯◯_pathのヘルパが自動で出来るのでもう少しきれいに書けると思いますよ

https://github.com/tomomih217/dacode/blob/378e1a02836db9dcf5bac2359052de59348532fc/app/controllers/scores_controller.rb#L5

このような直接的なSQLの書き方はあまりよろしくないのと2や1といった数値を直接いれる（これをマジックナンバーと言います）のはメンテがしづらくなり推奨されていないのでenumや定数をうまく使いましょう

```
LEVEL = 1 
def index
    @lv1_records = Record.giveup.where(level_id: LEVEL).includes(:user).order('(updated_at - created_at) asc')
  end
```

https://github.com/tomomih217/dacode/blob/378e1a02836db9dcf5bac2359052de59348532fc/app/models/record.rb#L9

こちらもenumのメソッドを使いましょう
```
return if trial?
```

* ロジックは色々と工夫されているのとテストも書かれているので、機能追加が一通り終わった後にRubocopを通してコードをきれいに整形し、READMEにスクショを貼るなどしてこちらも整えたら就活ウケもよくなるかなと思います。

**Comment by tomomih217** [comment]
レビューありがとうございます！
やはり難易度高いですか…。クリアまでフォローするようなヒントを設けるなどして、お試しの難易度を下げるよう対応したいと思います。
コードのご指摘についても、一つずつ対応したいと思います。取り急ぎお礼まで。
